### PR TITLE
Workflow to update gh-pages

### PR DESCRIPTION
**Pull request by ephemient**

### CODE REVIEW

**Comment by ephemient** [comment]
Sorry about the force pushes, Actions are hard to debug locally. [Here](https://github.com/ephemient/advent-of-code-2020/runs/1545152897) it succeeded and wrote a [commit](https://github.com/ephemient/advent-of-code-2020/commit/9c90434f98a3a093bcfc08e5c192192578bf1f72).

**Comment by mstksg** [comment]
Thanks!  Let's see how it goes :O

**Comment by mstksg** [comment]
how 2 merge again

**Comment by mstksg** [comment]
D:

**Pull request merged**
